package ecoaegtnh.client.model;

/**
 * Baked in-game geometry for the E-Storage Drive Bay (generated by
 * models/gen_drive_bay_java.py from models/drive_bay_geo.json - do not edit by hand).
 * <p>
 * Coordinate space: MC unit space, front face at z = 1, up = +y, block in [0,1]^3.
 * Each material is a triangle soup: POS holds 9 floats per triangle
 * (3 verts x xyz); UV holds 6 floats per triangle (u,v per vert) or null.
 */
public final class DriveBayGeometry {

    public static final int M_SHELL = 0;
    public static final int M_FRONT = 1;
    public static final int M_BEZEL = 2;
    public static final int M_HIGHLIGHT = 3;
    public static final int M_CAVITY = 4;
    public static final int M_CAVITYBACK = 5;
    public static final int M_CONTACTS = 6;
    public static final int M_CYAN = 7;
    public static final int M_LEDS = 8;
    public static final int M_CELLEDGE = 9;
    public static final int M_CELLFRONT = 10;
    public static final int MATERIAL_COUNT = 11;

    /** Triangles per material (indexed by M_*). */
    public static final int[] TRIANGLES = { 10, 8, 16, 4, 8, 2, 6, 2, 6, 10, 2, };

    /** Per-material RGB (0-255) or null for textured (shell) / dynamic (leds, cellFront). */
    public static final int[][] COLOR = { { 57, 58, 59 }, { 57, 58, 59 }, { 83, 85, 87 }, { 113, 116, 118 },
        { 34, 36, 41 }, { 28, 30, 32 }, { 250, 180, 85 }, { 77, 195, 255 }, { 12, 234, 76 }, { 45, 46, 48 },
        { 77, 195, 255 }, };

    /** Per-material emissive flag (drawn full-bright). */
    public static final boolean[] EMISSIVE = { false, false, false, false, false, false, true, true, true, false,
        true, };

    /** Per-material dynamic flag (colour set by the renderer per state). */
    public static final boolean[] DYNAMIC = { false, false, false, false, false, false, false, false, true, false,
        true, };

    /** Per-material triangle soup: 9 floats per triangle (xyz xyz xyz). */
    public static final float[][] POS = {
        new float[] { 1f, 0f, 0f, 1f, 0f, 1f, 1f, 1f, 1f, 1f, 0f, 0f, 1f, 1f, 1f, 1f, 1f, 0f, 0f, 1f, 0f, 0f, 1f, 1f,
            0f, 0f, 1f, 0f, 1f, 0f, 0f, 0f, 1f, 0f, 0f, 0f, 0f, 0f, 0f, 1f, 0f, 0f, 1f, 1f, 0f, 0f, 0f, 0f, 1f, 1f, 0f,
            0f, 1f, 0f, 0f, 1f, 1f, 0f, 1f, 0f, 1f, 1f, 0f, 0f, 1f, 1f, 1f, 1f, 0f, 1f, 1f, 1f, 0f, 0f, 0f, 0f, 0f, 1f,
            1f, 0f, 1f, 0f, 0f, 0f, 1f, 0f, 1f, 1f, 0f, 0f, },
        new float[] { 1f, 1f, 1f, 0f, 1f, 1f, 0f, 0.684375f, 1f, 1f, 1f, 1f, 0f, 0.684375f, 1f, 1f, 0.684375f, 1f, 1f,
            0.315625f, 1f, 0f, 0.315625f, 1f, 0f, 0f, 1f, 1f, 0.315625f, 1f, 0f, 0f, 1f, 1f, 0f, 1f, 0.15625f,
            0.684375f, 1f, 0f, 0.684375f, 1f, 0f, 0.315625f, 1f, 0.15625f, 0.684375f, 1f, 0f, 0.315625f, 1f, 0.15625f,
            0.315625f, 1f, 1f, 0.684375f, 1f, 0.84375f, 0.684375f, 1f, 0.84375f, 0.315625f, 1f, 1f, 0.684375f, 1f,
            0.84375f, 0.315625f, 1f, 1f, 0.315625f, 1f, },
        new float[] { 1f, 1f, 1.00125f, 0f, 1f, 1.00125f, 0f, 0.9375f, 1.00125f, 1f, 1f, 1.00125f, 0f, 0.9375f,
            1.00125f, 1f, 0.9375f, 1.00125f, 1f, 0.0625f, 1.00125f, 0f, 0.0625f, 1.00125f, 0f, 0f, 1.00125f, 1f,
            0.0625f, 1.00125f, 0f, 0f, 1.00125f, 1f, 0f, 1.00125f, 0.0625f, 0.9375f, 1.00125f, 0f, 0.9375f, 1.00125f,
            0f, 0.0625f, 1.00125f, 0.0625f, 0.9375f, 1.00125f, 0f, 0.0625f, 1.00125f, 0.0625f, 0.0625f, 1.00125f, 1f,
            0.9375f, 1.00125f, 0.9375f, 0.9375f, 1.00125f, 0.9375f, 0.0625f, 1.00125f, 1f, 0.9375f, 1.00125f, 0.9375f,
            0.0625f, 1.00125f, 1f, 0.0625f, 1.00125f, 0.84375f, 0.684375f, 1.00125f, 0.15625f, 0.684375f, 1.00125f,
            0.15625f, 0.715625f, 1.00125f, 0.84375f, 0.684375f, 1.00125f, 0.15625f, 0.715625f, 1.00125f, 0.84375f,
            0.715625f, 1.00125f, 0.84375f, 0.284375f, 1.00125f, 0.15625f, 0.284375f, 1.00125f, 0.15625f, 0.315625f,
            1.00125f, 0.84375f, 0.284375f, 1.00125f, 0.15625f, 0.315625f, 1.00125f, 0.84375f, 0.315625f, 1.00125f,
            0.1875f, 0.684375f, 1.00125f, 0.15625f, 0.684375f, 1.00125f, 0.15625f, 0.315625f, 1.00125f, 0.1875f,
            0.684375f, 1.00125f, 0.15625f, 0.315625f, 1.00125f, 0.1875f, 0.315625f, 1.00125f, 0.84375f, 0.684375f,
            1.00125f, 0.8125f, 0.684375f, 1.00125f, 0.8125f, 0.315625f, 1.00125f, 0.84375f, 0.684375f, 1.00125f,
            0.8125f, 0.315625f, 1.00125f, 0.84375f, 0.315625f, 1.00125f, },
        new float[] { 0.90625f, 0.9125f, 1.001875f, 0.09375f, 0.9125f, 1.001875f, 0.09375f, 0.9375f, 1.001875f,
            0.90625f, 0.9125f, 1.001875f, 0.09375f, 0.9375f, 1.001875f, 0.90625f, 0.9375f, 1.001875f, 0.90625f, 0.0625f,
            1.001875f, 0.09375f, 0.0625f, 1.001875f, 0.09375f, 0.0875f, 1.001875f, 0.90625f, 0.0625f, 1.001875f,
            0.09375f, 0.0875f, 1.001875f, 0.90625f, 0.0875f, 1.001875f, },
        new float[] { 0.15625f, 0.684375f, 1f, 0.15625f, 0.684375f, 0.765625f, 0.15625f, 0.315625f, 0.765625f, 0.15625f,
            0.684375f, 1f, 0.15625f, 0.315625f, 0.765625f, 0.15625f, 0.315625f, 1f, 0.84375f, 0.315625f, 1f, 0.84375f,
            0.315625f, 0.765625f, 0.84375f, 0.684375f, 0.765625f, 0.84375f, 0.315625f, 1f, 0.84375f, 0.684375f,
            0.765625f, 0.84375f, 0.684375f, 1f, 0.84375f, 0.684375f, 1f, 0.15625f, 0.684375f, 1f, 0.15625f, 0.684375f,
            0.765625f, 0.84375f, 0.684375f, 1f, 0.15625f, 0.684375f, 0.765625f, 0.84375f, 0.684375f, 0.765625f,
            0.84375f, 0.315625f, 1f, 0.15625f, 0.315625f, 1f, 0.15625f, 0.315625f, 0.765625f, 0.84375f, 0.315625f, 1f,
            0.15625f, 0.315625f, 0.765625f, 0.84375f, 0.315625f, 0.765625f, },
        new float[] { 0.84375f, 0.684375f, 0.765625f, 0.15625f, 0.684375f, 0.765625f, 0.15625f, 0.315625f, 0.765625f,
            0.84375f, 0.684375f, 0.765625f, 0.15625f, 0.315625f, 0.765625f, 0.84375f, 0.315625f, 0.765625f, },
        new float[] { 0.71875f, 0.34375f, 0.7875f, 0.28125f, 0.34375f, 0.7875f, 0.28125f, 0.315625f, 0.7875f, 0.71875f,
            0.34375f, 0.7875f, 0.28125f, 0.315625f, 0.7875f, 0.71875f, 0.315625f, 0.7875f, 0.71875f, 0.315625f,
            0.771875f, 0.28125f, 0.315625f, 0.771875f, 0.28125f, 0.315625f, 0.7875f, 0.71875f, 0.315625f, 0.771875f,
            0.28125f, 0.315625f, 0.7875f, 0.71875f, 0.315625f, 0.7875f, 0.28125f, 0.34375f, 0.771875f, 0.71875f,
            0.34375f, 0.771875f, 0.71875f, 0.315625f, 0.771875f, 0.28125f, 0.34375f, 0.771875f, 0.71875f, 0.315625f,
            0.771875f, 0.28125f, 0.315625f, 0.771875f, },
        new float[] { 0.6875f, 0.58125f, 0.76875f, 0.3125f, 0.58125f, 0.76875f, 0.3125f, 0.68125f, 0.76875f, 0.6875f,
            0.58125f, 0.76875f, 0.3125f, 0.68125f, 0.76875f, 0.6875f, 0.68125f, 0.76875f, },
        new float[] { 0.375f, 0.971875f, 1.0025f, 0.625f, 0.971875f, 1.0025f, 0.625f, 0.99375f, 1.0025f, 0.375f,
            0.971875f, 1.0025f, 0.625f, 0.99375f, 1.0025f, 0.375f, 0.99375f, 1.0025f, 0.10625f, 0.53125f, 1.0025f,
            0.14375f, 0.53125f, 1.0025f, 0.14375f, 0.46875f, 1.0025f, 0.10625f, 0.53125f, 1.0025f, 0.14375f, 0.46875f,
            1.0025f, 0.10625f, 0.46875f, 1.0025f, 0.85625f, 0.53125f, 1.0025f, 0.89375f, 0.53125f, 1.0025f, 0.89375f,
            0.46875f, 1.0025f, 0.85625f, 0.53125f, 1.0025f, 0.89375f, 0.46875f, 1.0025f, 0.85625f, 0.46875f, 1.0025f, },
        new float[] { 0.65625f, 0.575f, 0.8125f, 0.34375f, 0.575f, 0.8125f, 0.34375f, 0.575f, 0.8625f, 0.65625f, 0.575f,
            0.8125f, 0.34375f, 0.575f, 0.8625f, 0.65625f, 0.575f, 0.8625f, 0.34375f, 0.425f, 0.8625f, 0.34375f, 0.425f,
            0.8125f, 0.65625f, 0.425f, 0.8125f, 0.34375f, 0.425f, 0.8625f, 0.65625f, 0.425f, 0.8125f, 0.65625f, 0.425f,
            0.8625f, 0.34375f, 0.575f, 0.8125f, 0.34375f, 0.575f, 0.8625f, 0.34375f, 0.425f, 0.8625f, 0.34375f, 0.575f,
            0.8125f, 0.34375f, 0.425f, 0.8625f, 0.34375f, 0.425f, 0.8125f, 0.65625f, 0.575f, 0.8625f, 0.65625f, 0.575f,
            0.8125f, 0.65625f, 0.425f, 0.8125f, 0.65625f, 0.575f, 0.8625f, 0.65625f, 0.425f, 0.8125f, 0.65625f, 0.425f,
            0.8625f, 0.65625f, 0.425f, 0.8125f, 0.34375f, 0.425f, 0.8125f, 0.34375f, 0.575f, 0.8125f, 0.65625f, 0.425f,
            0.8125f, 0.34375f, 0.575f, 0.8125f, 0.65625f, 0.575f, 0.8125f, },
        new float[] { 0.65625f, 0.575f, 0.8625f, 0.34375f, 0.575f, 0.8625f, 0.34375f, 0.425f, 0.8625f, 0.65625f, 0.575f,
            0.8625f, 0.34375f, 0.425f, 0.8625f, 0.65625f, 0.425f, 0.8625f, }, };

    /** Per-material UVs: 6 floats per triangle (uv uv uv) or null. */
    public static final float[][] UV = { new float[] { 0f, 0f, 1f, 0f, 1f, 1f, 0f, 0f, 1f, 1f, 0f, 1f, 0f, 0f, 1f, 0f,
        1f, 1f, 0f, 0f, 1f, 1f, 0f, 1f, 0f, 0f, 1f, 0f, 1f, 1f, 0f, 0f, 1f, 1f, 0f, 1f, 0f, 0f, 1f, 0f, 1f, 1f, 0f, 0f,
        1f, 1f, 0f, 1f, 0f, 0f, 1f, 0f, 1f, 1f, 0f, 0f, 1f, 1f, 0f, 1f, }, null, null, null, null, null, null, null,
        null, null, null, };

    private DriveBayGeometry() {}
}
